name = "ShiftedProximalOperators"
uuid = "d4fd37fa-580c-4e43-9b30-361c21aae263"
authors = ["rjbaraldi <rbaraldi@uw.edu>"]
version = "0.1.0"

[deps]
ProximalOperators = "a725b495-10eb-56fe-b38b-717eba820537"
Roots = "f2b01f46-fcfa-551c-844a-d8ac1e96c665"

[compat]
ProximalOperators = "0.14.0"
Roots = "^1.0.0"
julia = "^1.3.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
